// Generated by gencpp from file my_pkg/reach_positionFeedback.msg
// DO NOT EDIT!


#ifndef MY_PKG_MESSAGE_REACH_POSITIONFEEDBACK_H
#define MY_PKG_MESSAGE_REACH_POSITIONFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_pkg
{
template <class ContainerAllocator>
struct reach_positionFeedback_
{
  typedef reach_positionFeedback_<ContainerAllocator> Type;

  reach_positionFeedback_()
    : distance(0)  {
    }
  reach_positionFeedback_(const ContainerAllocator& _alloc)
    : distance(0)  {
  (void)_alloc;
    }



   typedef int32_t _distance_type;
  _distance_type distance;




  typedef boost::shared_ptr< ::my_pkg::reach_positionFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_pkg::reach_positionFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct reach_positionFeedback_

typedef ::my_pkg::reach_positionFeedback_<std::allocator<void> > reach_positionFeedback;

typedef boost::shared_ptr< ::my_pkg::reach_positionFeedback > reach_positionFeedbackPtr;
typedef boost::shared_ptr< ::my_pkg::reach_positionFeedback const> reach_positionFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_pkg::reach_positionFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_pkg::reach_positionFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'my_pkg': ['/home/virgile/workspace/groneROSworkshop/my_catkin_ws/devel/share/my_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_pkg::reach_positionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_pkg::reach_positionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_pkg::reach_positionFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_pkg::reach_positionFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_pkg::reach_positionFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_pkg::reach_positionFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_pkg::reach_positionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "680f8923bb6b23ec7057fffc11ea7b34";
  }

  static const char* value(const ::my_pkg::reach_positionFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x680f8923bb6b23ecULL;
  static const uint64_t static_value2 = 0x7057fffc11ea7b34ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_pkg::reach_positionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_pkg/reach_positionFeedback";
  }

  static const char* value(const ::my_pkg::reach_positionFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_pkg::reach_positionFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#feedback\n\
int32 distance\n\
\n\
";
  }

  static const char* value(const ::my_pkg::reach_positionFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_pkg::reach_positionFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reach_positionFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_pkg::reach_positionFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_pkg::reach_positionFeedback_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<int32_t>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_PKG_MESSAGE_REACH_POSITIONFEEDBACK_H
