; Auto-generated. Do not edit!


(cl:in-package my_pkg-msg)


;//! \htmlinclude reach_positionResult.msg.html

(cl:defclass <reach_positionResult> (roslisp-msg-protocol:ros-message)
  ((time
    :reader time
    :initarg :time
    :type cl:integer
    :initform 0))
)

(cl:defclass reach_positionResult (<reach_positionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <reach_positionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'reach_positionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_pkg-msg:<reach_positionResult> is deprecated: use my_pkg-msg:reach_positionResult instead.")))

(cl:ensure-generic-function 'time-val :lambda-list '(m))
(cl:defmethod time-val ((m <reach_positionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_pkg-msg:time-val is deprecated.  Use my_pkg-msg:time instead.")
  (time m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <reach_positionResult>) ostream)
  "Serializes a message object of type '<reach_positionResult>"
  (cl:let* ((signed (cl:slot-value msg 'time)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <reach_positionResult>) istream)
  "Deserializes a message object of type '<reach_positionResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'time) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<reach_positionResult>)))
  "Returns string type for a message object of type '<reach_positionResult>"
  "my_pkg/reach_positionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'reach_positionResult)))
  "Returns string type for a message object of type 'reach_positionResult"
  "my_pkg/reach_positionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<reach_positionResult>)))
  "Returns md5sum for a message object of type '<reach_positionResult>"
  "86f5c1180cd9d94f9d1de0b211fa9fd2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'reach_positionResult)))
  "Returns md5sum for a message object of type 'reach_positionResult"
  "86f5c1180cd9d94f9d1de0b211fa9fd2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<reach_positionResult>)))
  "Returns full string definition for message of type '<reach_positionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'reach_positionResult)))
  "Returns full string definition for message of type 'reach_positionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%int32 time~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <reach_positionResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <reach_positionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'reach_positionResult
    (cl:cons ':time (time msg))
))
