; Auto-generated. Do not edit!


(cl:in-package my_pkg-msg)


;//! \htmlinclude reach_positionGoal.msg.html

(cl:defclass <reach_positionGoal> (roslisp-msg-protocol:ros-message)
  ((x
    :reader x
    :initarg :x
    :type cl:integer
    :initform 0)
   (y
    :reader y
    :initarg :y
    :type cl:integer
    :initform 0))
)

(cl:defclass reach_positionGoal (<reach_positionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <reach_positionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'reach_positionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_pkg-msg:<reach_positionGoal> is deprecated: use my_pkg-msg:reach_positionGoal instead.")))

(cl:ensure-generic-function 'x-val :lambda-list '(m))
(cl:defmethod x-val ((m <reach_positionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_pkg-msg:x-val is deprecated.  Use my_pkg-msg:x instead.")
  (x m))

(cl:ensure-generic-function 'y-val :lambda-list '(m))
(cl:defmethod y-val ((m <reach_positionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_pkg-msg:y-val is deprecated.  Use my_pkg-msg:y instead.")
  (y m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <reach_positionGoal>) ostream)
  "Serializes a message object of type '<reach_positionGoal>"
  (cl:let* ((signed (cl:slot-value msg 'x)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
  (cl:let* ((signed (cl:slot-value msg 'y)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <reach_positionGoal>) istream)
  "Deserializes a message object of type '<reach_positionGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'x) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'y) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<reach_positionGoal>)))
  "Returns string type for a message object of type '<reach_positionGoal>"
  "my_pkg/reach_positionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'reach_positionGoal)))
  "Returns string type for a message object of type 'reach_positionGoal"
  "my_pkg/reach_positionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<reach_positionGoal>)))
  "Returns md5sum for a message object of type '<reach_positionGoal>"
  "bd7b43fd41d4c47bf5c703cc7d016709")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'reach_positionGoal)))
  "Returns md5sum for a message object of type 'reach_positionGoal"
  "bd7b43fd41d4c47bf5c703cc7d016709")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<reach_positionGoal>)))
  "Returns full string definition for message of type '<reach_positionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 x~%int32 y~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'reach_positionGoal)))
  "Returns full string definition for message of type 'reach_positionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 x~%int32 y~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <reach_positionGoal>))
  (cl:+ 0
     4
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <reach_positionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'reach_positionGoal
    (cl:cons ':x (x msg))
    (cl:cons ':y (y msg))
))
