; Auto-generated. Do not edit!


(cl:in-package my_pkg-msg)


;//! \htmlinclude reach_positionActionGoal.msg.html

(cl:defclass <reach_positionActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type my_pkg-msg:reach_positionGoal
    :initform (cl:make-instance 'my_pkg-msg:reach_positionGoal)))
)

(cl:defclass reach_positionActionGoal (<reach_positionActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <reach_positionActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'reach_positionActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_pkg-msg:<reach_positionActionGoal> is deprecated: use my_pkg-msg:reach_positionActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <reach_positionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_pkg-msg:header-val is deprecated.  Use my_pkg-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <reach_positionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_pkg-msg:goal_id-val is deprecated.  Use my_pkg-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <reach_positionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_pkg-msg:goal-val is deprecated.  Use my_pkg-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <reach_positionActionGoal>) ostream)
  "Serializes a message object of type '<reach_positionActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <reach_positionActionGoal>) istream)
  "Deserializes a message object of type '<reach_positionActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<reach_positionActionGoal>)))
  "Returns string type for a message object of type '<reach_positionActionGoal>"
  "my_pkg/reach_positionActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'reach_positionActionGoal)))
  "Returns string type for a message object of type 'reach_positionActionGoal"
  "my_pkg/reach_positionActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<reach_positionActionGoal>)))
  "Returns md5sum for a message object of type '<reach_positionActionGoal>"
  "08e769ea8f09d0b66e6c4c03983c9418")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'reach_positionActionGoal)))
  "Returns md5sum for a message object of type 'reach_positionActionGoal"
  "08e769ea8f09d0b66e6c4c03983c9418")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<reach_positionActionGoal>)))
  "Returns full string definition for message of type '<reach_positionActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%reach_positionGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: my_pkg/reach_positionGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 x~%int32 y~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'reach_positionActionGoal)))
  "Returns full string definition for message of type 'reach_positionActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%reach_positionGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: my_pkg/reach_positionGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%int32 x~%int32 y~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <reach_positionActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <reach_positionActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'reach_positionActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
