; Auto-generated. Do not edit!


(cl:in-package my_pkg-msg)


;//! \htmlinclude reach_positionFeedback.msg.html

(cl:defclass <reach_positionFeedback> (roslisp-msg-protocol:ros-message)
  ((distance
    :reader distance
    :initarg :distance
    :type cl:integer
    :initform 0))
)

(cl:defclass reach_positionFeedback (<reach_positionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <reach_positionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'reach_positionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_pkg-msg:<reach_positionFeedback> is deprecated: use my_pkg-msg:reach_positionFeedback instead.")))

(cl:ensure-generic-function 'distance-val :lambda-list '(m))
(cl:defmethod distance-val ((m <reach_positionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_pkg-msg:distance-val is deprecated.  Use my_pkg-msg:distance instead.")
  (distance m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <reach_positionFeedback>) ostream)
  "Serializes a message object of type '<reach_positionFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'distance)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <reach_positionFeedback>) istream)
  "Deserializes a message object of type '<reach_positionFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'distance) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<reach_positionFeedback>)))
  "Returns string type for a message object of type '<reach_positionFeedback>"
  "my_pkg/reach_positionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'reach_positionFeedback)))
  "Returns string type for a message object of type 'reach_positionFeedback"
  "my_pkg/reach_positionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<reach_positionFeedback>)))
  "Returns md5sum for a message object of type '<reach_positionFeedback>"
  "680f8923bb6b23ec7057fffc11ea7b34")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'reach_positionFeedback)))
  "Returns md5sum for a message object of type 'reach_positionFeedback"
  "680f8923bb6b23ec7057fffc11ea7b34")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<reach_positionFeedback>)))
  "Returns full string definition for message of type '<reach_positionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 distance~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'reach_positionFeedback)))
  "Returns full string definition for message of type 'reach_positionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 distance~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <reach_positionFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <reach_positionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'reach_positionFeedback
    (cl:cons ':distance (distance msg))
))
